#!/bin/bash
mv Gemini_Generated_Image_1dk8001dk8001dk8.png hero-celebration-moment.png
mv Gemini_Generated_Image_28eby828eby828eb.png travel-cappadocia-balloons.png
mv Gemini_Generated_Image_329ayf329ayf329a.png seasonal-autumn-bebek-park.png
mv Gemini_Generated_Image_3x3d3j3x3d3j3x3d.png intimate-rainy-window.png
mv Gemini_Generated_Image_5t36zf5t36zf5t36.png wedding-preparation-dress.png
mv Gemini_Generated_Image_8yehxt8yehxt8yeh.png wedding-first-dance.png
mv Gemini_Generated_Image_avpbkaavpbkaavpb.png seasonal-winter-snow-kiss.png
mv Gemini_Generated_Image_bcj9lcbcj9lcbcj9.png home-morning-coffee-balcony.png
mv Gemini_Generated_Image_bkcq4bbkcq4bbkcq.png travel-antalya-beach-sunset.png
mv Gemini_Generated_Image_cbacpwcbacpwcbac.png activity-art-class-painting.png
mv Gemini_Generated_Image_e9ukx2e9ukx2e9uk.png activity-hiking-uludag.png
mv Gemini_Generated_Image_eze0emeze0emeze0.png wedding-first-kiss-married.png
mv Gemini_Generated_Image_g6w2dqg6w2dqg6w2.png detail-love-letter-hands.png
mv Gemini_Generated_Image_hq5cthq5cthq5cth.png intimate-slow-dance-home.png
mv Gemini_Generated_Image_ib21d2ib21d2ib21.png wedding-cake-cutting.png
mv Gemini_Generated_Image_ii6wf4ii6wf4ii6w.png detail-couple-initials-tree.png
mv Gemini_Generated_Image_ipze7tipze7tipze.png anniversary-romantic-dinner.png
mv Gemini_Generated_Image_l53coal53coal53c.png memory-first-kiss-balat.png
mv Gemini_Generated_Image_lfj2wplfj2wplfj2.png detail-wedding-rings-hands.png
mv Gemini_Generated_Image_od96hlod96hlod96.png wedding-ceremony-vows.png
mv Gemini_Generated_Image_omg966omg966omg9.png seasonal-summer-beach-sunset-embrace.png
mv Gemini_Generated_Image_p3x0wdp3x0wdp3x0.png home-reading-together-bedroom.png
mv Gemini_Generated_Image_q8eaypq8eaypq8ea.png memory-first-meeting-bookstore.png
mv Gemini_Generated_Image_r2auwrr2auwrr2au.png hero-intimate-portrait.png
mv Gemini_Generated_Image_r2r1xjr2r1xjr2r1.png home-cooking-together-kitchen.png
mv Gemini_Generated_Image_s2tqy9s2tqy9s2tq.png birthday-surprise-ela.png
mv Gemini_Generated_Image_sb4tvssb4tvssb4t.png proposal-ring-closeup.png
mv Gemini_Generated_Image_ts048pts048pts04.png travel-pamukkale-travertines.png
mv Gemini_Generated_Image_tumr2ttumr2ttumr.png intimate-morning-bed-cuddle.png
mv Gemini_Generated_Image_v2wbsv2wbsv2wbsv.png memory-first-date-bosphorus.png
mv Gemini_Generated_Image_vaypoovaypoovayp.png engagement-party-toast.png
mv Gemini_Generated_Image_vnzzorvnzzorvnzz.png activity-concert-festival.png
mv Gemini_Generated_Image_w3dqmow3dqmow3dq.png bonus-city-stroll.png
mv Gemini_Generated_Image_x6b8lhx6b8lhx6b8.png proposal-celebration-champagne.png
mv Gemini_Generated_Image_xf0uhuxf0uhuxf0u.png hero-main-banner.png
mv Gemini_Generated_Image_y8cecmy8cecmy8ce.png home-movie-night-couch.png
mv Gemini_Generated_Image_yn9fbbyn9fbbyn9f.png activity-cycling-princes-islands.png
mv Gemini_Generated_Image_yosrs0yosrs0yosr.png proposal-moment-cappadocia.png
mv Gemini_Generated_Image_yxzqvxyxzqvxyxzq.png seasonal-spring-tulip-garden.png

# Remove duplicate
rm "Gemini_Generated_Image_xf0uhuxf0uhuxf0u (1).png"
